version: '3.8'
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=${TZ:-America/Los_Angeles}
      - VERSION=docker
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ${CONF_ROOT:-.}/plex:/config
      - ${MEDIA_ROOT}/TV Shows:/tv
      - ${MEDIA_ROOT}/Movies:/movies
      - ${MEDIA_ROOT}/Music:/music
    restart: unless-stopped
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=${TZ:-America/Los_Angeles}
    volumes:
      - ${CONF_ROOT:-.}/tautulli:/config
    ports:
      - ${TAUTULLI_UI:-8181}:8181
    restart: unless-stopped